#pragma once

#include "CoreMinimal.h"
#include "IDetailCustomization.h"

class IDetailCategoryBuilder;
class IDetailLayoutBuilder;
class SBox;
class UMazeEdModeSettings;

/**
 *  The mode panel.
 *
 *  It is a customization and not a plain widget because there is no other way in: the sections are
 *  generated by the property system from UPROPERTY fields and CallInEditor functions, and changing
 *  any of it means taking part in that generation. Three things need it.
 *
 *  1. The group order. Categories are laid out in the order they are created, and CallInEditor
 *     buttons create theirs alphabetically — which would give Advanced, Brush, Build, Display,
 *     Snapshot, Target. The panel should read the way the job goes instead, so the order is set
 *     explicitly with SetSortOrder.
 *
 *  2. Disabled buttons. A CallInEditor button is always enabled, and three of them must not be:
 *     Generate Maze against a grid whose generator is the manual one, and the edit cycle before
 *     there is a maze to edit. Those three are built here by hand, their enabled state bound to
 *     the settings so it follows the target without anyone refreshing the panel.
 *
 *  3. The surface variant palette — a row of colour swatches, which was never going to come out
 *     of a plain integer property.
 */
class FMazeEdModeSettingsDetails : public IDetailCustomization
{
public:
	static TSharedRef<IDetailCustomization> MakeInstance();

	virtual ~FMazeEdModeSettingsDetails() override;

	virtual void CustomizeDetails(IDetailLayoutBuilder& DetailBuilder) override;

private:
	/**
	 *  Rebuilds the swatch row for the current paint type.
	 *
	 *  Only the row is rebuilt, never the whole panel. Forcing a details refresh on every settings
	 *  change would be simpler to write and would steal focus out of a numeric field while it is
	 *  being typed into.
	 */
	void RebuildPalette();

	/** Rebuilds both swatch rows. Bound to the settings delegate. */
	void OnSettingsChanged();

	/** The Generate button, plus the line that says why it is off when it is. */
	void BuildGenerateRow(IDetailCategoryBuilder& Category);

	/** The object type swatches, and the line saying what is selected and how much is placed. */
	void BuildObjectPalette(IDetailCategoryBuilder& Category);
	void RebuildObjectPalette();

	/** Change Current Maze and Apply Changes To Current Maze, both off until a maze exists. */
	void BuildEditRows(IDetailCategoryBuilder& Category);

	TWeakObjectPtr<UMazeEdModeSettings> Settings;

	/** Containers whose content is swapped out on rebuild. */
	TSharedPtr<SBox> PaletteBox;
	TSharedPtr<SBox> ObjectBox;

	FDelegateHandle SettingsChangedHandle;
};
